
begin
    println("                                  ;=**└└└└²*ª═╓")
    print("                               ╓*└ ") 
    printstyled("╓@Φ╬Φ╗,", color = :red) 
    println("     -*▄")
    print("                             ,▀   ")
    printstyled("╬▓▓▓▓▓▓▓▌", color = :red)
    println("       ╙╕")
    print("                            ╓╛   ")
    printstyled("▐▓▓▓▓▓▓▓▓▓", color = :red)
    println("         φ")
    print("                            ▌     ")
    printstyled("▀▓▓▓▓▓▓▓M ", color = :red) 
    printstyled("╓▄▓▓▄w", color = :green)
    println("   w")
    print("                           ▐        ")
    printstyled("'╙╜╜' ", color = :red)
    printstyled("╓█▓▓▓▓▓▓█╕", color = :green)
    println(" ▌")
    print("                           ▐     ")
    printstyled(",╗Φ╬Φ╗,  ", color = 5) 
    printstyled("█▓▓▓▓▓▓▓▓█", color = :green)
    println(" ▌")
    print("             ,¿+≈=ww¡       ▌   ")
    printstyled("╬╫╫╫╫╫╫╫▌ ", color = 5)
    printstyled("╙█▓▓▓▓▓▓█'", color = :green) 
    println(",L")
    print("         ╓═╙`         └Yw   ╙╕  ")
    printstyled("╫╫╫╫╫╫╫╫╫H  ", color = 5)
    printstyled("╙▀▀▀▀└ ", color = :green) 
    println(",▀")
    print("       /Γ")
    printstyled(",╓▄▄▄╓", color = :green)
    print("           \\,  % ")
    printstyled("╚╫╫╫╫╫╫╫M", color = 5)
    println("         ▄▌")
    print("     ,▀ ")
    printstyled("▓▓▓▓▓▓▓█╕   ", color = :green) 
    printstyled("╔Φ╬╬╬N,", color = 5)
    print("'w  ╙%ç")
    printstyled("'╨╜╜^", color = 5)
    println("        ,«'   └²**═≈w;")
    print("    .┘ ")
    printstyled("╢▓▓▓▓▓▓▓▓▓ ", color = :green)
    printstyled(".╣╫╫╫╫╫╫╫N ", color = 5)
    println("▌    Jf═ww╓;╓╓÷═f┘                └²**═≈w¡,")
    print("    █  ")
    printstyled("╙█▓▓▓▓▓▓▓▌ ", color = :green) 
    printstyled("▐╫╫╫╫╫╫╫╫╫ ", color = 5) 
    println("▐   *                                       └└'*═≈w╓,")
    print("    ▌    ")
    printstyled("╙▀██▀▀-   ", color = :green) 
    printstyled("╚╫╫╫╫╫╫╣┘", color = 5)
    println("╙T=                                                    ¬└²*══÷╓;")
    print("    █       ") 
    printstyled(",φ╬▓▓▓Nµ ", color = :red) 
    printstyled("`╙╙║`   ", color = 5)
    println("▐                      ╔███                                     -└²**═ww┌")
    print("     ▄     ")
    printstyled("╔▓▓▓▓▓▓▓▓▌", color = :red) 
    println("    w   ▌     ███▌             ║███")
    print("     '▄    ")
    printstyled("╟▓▓▓▓▓▓▓▓▓", color = :red) 
    println("    ▌ ,▀      ███▌ ╓▄▄▄   ╓▄▄▄ ║███    ▄▄▄▄▄     ╓▄▄▄▄▄▄   ╓▄▄▄ ▄▄▄▄    ╓▄▄▄▄▄▄")
    print("       ╘w   ")
    printstyled("▀▓▓▓▓▓▓▓'", color = :red)
    println("    ▐A-       ███▌ ║███   ║███ ║███  ██▌  ╙███▄ ███   ███▌ ║███▀▀▀████ ███   ███")
    print("         ╙═w, ")
    printstyled("'╙╙'", color = :red)
    println("    ╓═Γ ▌        ███▌ ║███   ║███ ║███ ███▀▀▀▀▀▀▀▀     ▄▄███▌ ║███   ▐███     ▄▄███▌")
    println("             ¬╙²***└└     ╞        ███▌ ║███   ║███ ║███ ███▌        ▄███▀ ███▌ ║███   ▐███ ▄███▀ ███▌")
    println("                          ▐⌐ ▄     ███▌ ▐███  ╓████ ║███ ╙███▄  ╓▄█▀ ███▄  ███▌ ║███   ▐███▐███▄  ███▌")
    println("                           ▌ ▀▀▀███▀▀    ╙▀██▀▀▀▀▀▀ ╚▀▀▀   ▀▀███▀▀   ╙▀███▀▀▀▀  ╚▀▀▀   ╘▀▀▀╙▀▀███▀▀▀▀ ")
end