using RadiationDetectorDSP
# using PlotlyJS
using Plots
using LegendHDF5IO
using Unitful
using RadiationDetectorSignals
using Statistics
using GLM
using LinearRegression
using InverseFunctions
using ArraysOfArrays
using TypedTables
using BenchmarkTools
using LaTeXStrings
using Measures
using HDF5
using ProgressBars
using ProgressMeter
using FilePathsBase
using Formatting
using Base
using ConfParser
using IntervalSets
using ThreadsX
using DataFrames
using ElasticArrays
using JSON
using Distributions
using StatsPlots
using StatsBase
using RadiationSpectra
using SpecialFunctions
using PDFmerger
using LegendSpecFits
using Optim
using LinearAlgebra
using StructArrays
using ValueShapes
using StatsBase
using Distributions
using LinearAlgebra
using BAT
using Roots
using LsqFit;