
# log texts that are static in each log report
const decay_time_log_text = """## Decay Time Extraction
This is the log for the decay time extraction. The algorithm loads the FEP data of each channel.
After a mini DSP, the decay times are extracted by fittiing an exponential function to the tail.
Then, the distribution is truncated around the peak to fit a truncated gaussian function.
The centroid of the distribution is extracted as the decay time.
"""

const flt_optimization_log_text = """## Filter Optimization
This is the log for the energy filter optimization. The algorithm loads the FEP data of each channel.
After a mini DSP, the optimal rise time is determined by performing a noise sweep on the baseline and look for minimal ENC with a fixed flat-top time.
Then, the optimal rise time is used for a mini DSP while sweeping through flat-top times and selecting the one which has minimal FWHM at the FEP.
"""

const sg_flt_optimization_log_text = """## SG window length optimization
This is the log for the savitzky-golay filter optimization for the PSD analysis. The processing involves
a small DSP routine on the waveforms in the DEP and SEP, a simple AoE cut for different window lengths
and the calculation of the survival fraction in the SEP after a simple PSD cut on the DEP. Then, the 
window length with the lowest survival fraction is chosen."""

const dsp_cal_log_text = """## DSP
This is the log for the dsp. The algorithm iterates through each file and process within each file each detector separate."""

const hit_cal_log_text = """## Hit Cal QC generation
This is the log for the qualtiy cuts generation for calibration data. The algorithm generates the QC cuts and saves a hit file per detector
for the following processing."""

const energy_ctc_log_text = """## CT Correction
This is the log for the charge trapping correction. The algorithm loads all data for a channel and performs the correction while optimizing maximum height and FWHM of a defined peak in the energy spectrum.
Before the parameters are extracted, QC cuts are applied to increase the quality of the data."""

const energy_log_text = """ ## Energy Calibration
This is the log for the energy calibration. The algorithm loads all data for a channel and performs a energy calibration while fitting peaks identified in the spectrum and returning 
calibration constant and resolution.
Before the parameters are extracted, QC cuts are applied to increase the quality of the data."""

const aoe_log_text = """## PSD calibration
This is the log for the PSD calibration for the AoE PSD analysis. The processing involves fitting the Compton bands of the AoE spectrum and fitting the resulting parameters with correction functions. The correction functions are then applied to the AoE spectrum. The resulting AoE spectrum is then saved to the hit file.
"""

const energy_part_log_text = """ ## Energy Partition Calibration
This is the log for the energy calibration for a partition. The algorithm loads all data for a channel and performs a energy calibration while fitting peaks identified in the spectrum and returning 
calibration constant and resolution for a full partition."""

const aoe_part_log_text = """ ## PSD CUT
This is the log for the PSD CUT generation for the AoE PSD analysis. The processing involves 
generating a cut that let's 90% of the events in the Tl-208 DEP pass. The cut is generated by
sweeping through different values of the cut and finding the root with 90% of the original peak counts."""